
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
          source-url: https://nuget.pkg.github.com/mjczone/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} #github action provided token

      - name: Set VERSION_NUMBER variable from tag
        run: echo "VERSION_NUMBER=${GITHUB_REF_NAME/v/}" >> $GITHUB_ENV

      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION_NUMBER}

      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION_NUMBER} --no-build

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION_NUMBER} --no-build --output nupkgs
        
      - name: Push
        run: dotnet nuget push nupkgs/${PACKAGE_ID}.${VERSION_NUMBER}.nupkg
        env:
          PACKAGE_ID: "DapperMatic"
